---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo
    db_host = odoo-db
    db_user = odoo
    db_password = odoo
    db_port = 5432
    admin_passwd = admin@17

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/odoo_data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-app
  template:
    metadata:
      labels:
        app: odoo-app
    spec:
      securityContext:        
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: odoo
          image: odoo:17
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: odoo-db
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          command:
            - odoo
            - -c
            - /etc/odoo.conf
            - -d
            - odoo
            - --init=base
            - --without-demo=all
          volumeMounts:
            - name: odoo-storage
              mountPath: /var/lib/odoo
            - name: extra-addons
              mountPath: /mnt/extra-addons
            - name: odoo-config
              mountPath: /etc/odoo.conf
              subPath: odoo.conf
      volumes:
        - name: odoo-storage
          persistentVolumeClaim:
            claimName: odoo-pvc
        - name: extra-addons
          hostPath:
            path: /mnt/odoo_addons
        - name: odoo-config
          configMap:
            name: odoo-config

---

apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: NodePort
  selector:
    app: odoo-app
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30007

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/pg_data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-db
  template:
    metadata:
      labels:
        app: odoo-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: odoo
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: odoo-db
spec:
  selector:
    app: odoo-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
